<main class="container mt-5">
    <h1 class="mb-5">Cadastro de Usuário</h1>
    <div class="mb-4"></div>
    <form action="" method="POST">
        <div class="mb-3">
            <label for="username" class="form-label">Username</label>
            <input type="email" class="form-control" name="username" id="username">
        </div>
        <div class="mb-3">
            <label for="passwd" class="form-label">Password</label>
            <input type="password" class="form-control" name="passwd" id="passwd">
        </div>
        <div class="mb-3">
            <label for="user_name" class="form-label">Nome Completo</label>
            <input type="email" class="form-control" name="user_name" id="user_name">
        </div>
        <div class="mb-3">
            <label for="permission" class="form-label">Nome Completo</label>
            <select class="form-select" id="permission" name="permission">
                <option value="1">Administrador</option>
                <option value="2">Usuário</option>
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

</main>