<div class="container mt-5">
    <h1 class="text-center mb-3">Listagem de Aulas</h1>
    <div class="row">
        <img class="col-2" src="<?= $this->viewData->school['school_logo'] ?>" alt="" style="max-width: 200px;">
        <h2 class="text-center display-6 col align-self-center"><?= $this->viewData->curse['curse_title'] ?></h2>
    </div>
    <div class="row justify-content-end mb-5 mt-5">
        <div class="col-2 ">
            <a href="add_class?id=
            <?= $this->viewData->curse['IDCURSE'] ?>" class="btn btn-success ">Adicionar Aula</a>
        </div>
        <div class="col-2">
            <a href="view_classes?id=<?= $this->viewData->curse['IDCURSE'] ?>" class="btn btn-success ">Visão completa</a>
        </div>
    </div>
    <hr>
    <div class="listagem-sem-cabecalho row">
        <?php $subtitle_temp = ''; ?>
        <?php foreach ($this->viewData->list_classes as $class) { ?>
            <?php if ($class['ID_SUBTITLE'] != '') {
                if ($class['ID_SUBTITLE'] != $subtitle_temp) {
                    $subtitle_temp = $class['ID_SUBTITLE'];
                    foreach ($this->viewData->subtitles as $subtitle) {
                        if ($subtitle_temp == $subtitle['IDSUBTITLE']) {
                            echo '<h3 class="text-center">' . $subtitle['subtitle'] . '</h3>';
                        }
                    }
                }
            } ?>
            <ul class="row justify-content-between">
                <div class="col-9 row flex-fill">
                    <li class="col-2"><?php $class_number = $class['class_number'];
                                        while (strlen($class_number) < 3) {
                                            $class_number = '0' . $class_number;
                                        }
                                        echo 'Aula ' . $class_number; ?></li>
                    <li class="col-9"> <?= $class['class_title'] ?></li>
                    <li class="col-1"> <?php foreach ($this->viewData->listagem_assuntos as $subject) {
                                            if ($subject['IDSUBJECT'] == $class['ID_SUBJECT']) {
                                                echo $subject['subject'];
                                            }
                                        } ?></li>
                </div>
                <div class="col-3 d-flex flex-row">
                    <li class="me-2">
                        <a class="btn btn-success" href="view_class?id=<?= $this->viewData->curse['IDCURSE'] ?>&class=<?= $class['IDCLASS'] ?>">
                            Ver aula
                        </a>
                    </li>
                    <li class="me-2">
                        <a class="btn btn-success" href="edit_class?id=<?= $this->viewData->curse['IDCURSE'] ?>&class=<?= $class['IDCLASS'] ?>">
                            Edit
                        </a>
                    </li>
                    <li class="me-2">
                        <a class="btn btn-danger" href="delete_class?id=<?= $this->viewData->curse['IDCURSE'] ?>&class=<?= $class['IDCLASS'] ?>">
                            Delete
                        </a>
                    </li>
                </div>

            </ul>
        <?php } ?>
    </div>
</div>