<div class="container mt-5">
    <div class="row">
        <img src="<?= $this->viewData->school['school_logo'] ?>" alt="" style="max-width: 200px;" class="col-2">
        <h1 class="text-center display-6 col align-self-center"><?= $this->viewData->curse['curse_title'] ?></h1>
    </div>
    <div class="row justify-content-end mb-5 mt-5">

        <div class="col-2">
            <a href="list_classes?id=<?= $this->viewData->curse['IDCURSE'] ?>" class="btn btn-success ">Voltar</a>
        </div>
    </div>

    <div class="row">

        <div class="card mb-3">
            <h5 class="card-header "><?php $class_number = $this->viewData->list_class['class_number'];
                                        while (strlen($class_number) < 3) {
                                            $class_number = '0' . $class_number;
                                        }
                                        echo 'Aula ' . $class_number; ?> -
                <?= $this->viewData->list_class['class_title'] ?></h5>
            <?php if (!empty($this->viewData->list_class['class_image_path'])) { ?>
                <img class="card-img-top align-self-center" src="
                    <?= $this->viewData->list_class['class_image_path'] ?>" alt="...">
            <?php } ?>
            <div class="card-body">
                <p class="card-text"><?= $this->viewData->list_class['class_notes'] ?></p>
                <?php if (!empty($this->viewData->list_class['class_path'])) { ?>
                    <a href="<?= $this->viewData->list_class['class_path'] ?>" target='_blank' class="btn btn-primary">Ver projeto</a>
                <?php } ?>
                <a href="edit_class?id=<?= $_GET['id'] ?>&class=<?= $_GET['class'] ?>" class="btn btn-secondary">Editar aula</a>
            </div>
            <div class="card-footer text-muted text-center">
                <div class="d-flex justify-content-between">
                    <p>
                        <?php foreach ($this->viewData->listagem_assuntos as $subject) {
                            if ($subject['IDSUBJECT'] == $this->viewData->list_class['ID_SUBJECT']) {
                                echo $subject['subject'];
                            }
                        } ?>
                    </p>
                    <p><?= $this->viewData->list_class['include_date'] ?></p>
                </div>
            </div>
        </div>

    </div>
</div>