<div class="container mt-5">
    <h1 class="text-center mb-3">Listagem de Aulas</h1>
    <h2><?= $this->viewData->curse['curse_title'] ?></h2>
    <div class="row justify-content-end mb-5">
        <div class="col-2 ">
            <a href="add_class?id=<?= $this->viewData->curse['IDCURSE'] ?>" class="btn btn-success ">Adicionar Aula</a>
        </div>
    </div>
    <hr>
    <div class="listagem-sem-cabecalho row">
        <?php foreach ($this->viewData->list_classes as $class) { ?>
            <ul class="justify-content-between ps-5 pe-5">
                <div class="row flex-fill">
                    <li class="col-1"><?= $class['class_number'] ?></li>
                    <li class="col-4"> <?= $class['class_title'] ?></li>
                </div>
                <div class="d-flex flex-row">
                    <li class="me-2"><a href="list_classes?id=<?= $curse['IDCURSE'] ?>" class="btn btn-success">Ver aulas</a></li>
                    <li class="me-2"><a href="edit_curse?id=<?= $curse['IDCURSE'] ?>" class="btn btn-success">Edit</a></li>
                    <li class="me-2"><a href="delete_curse?id=<?= $curse['IDCURSE'] ?>" class="btn btn-danger">Delete</a></li>
                </div>
            </ul>
        <?php } ?>
    </div>
</div>