<div class="container mt-5">
    <h1 class="text-center mb-3">Add Note</h1>

    <form action="save_note" method="POST">
        <div class="d-flex flex-row justify-content-between align-items-center mb-4">
            <div class="container">

                <label for="subject" class="form-label me-2">Assunto</label>
                <select class="form-select" name="id_subject" id="subject" aria-label="Default select example">
                    <?php foreach ($this->viewData->listagem_assuntos as $assunto) { ?>
                        <option value="<?= $assunto['IDSUBJECT'] ?>"><?= $assunto['subject'] ?></option>
                    <?php } ?>
                </select>
            </div>
            <div class="container">

                <label for="subject" class="form-label me-2">Tipo de texto</label>
                <select class="form-select" name="type_of_note" id="subject" aria-label="Default select example">
                    <option value="I">Instalação</option>
                    <option value="F">Configuração</option>
                    <option value="C">Comandos</option>
                    <option value="T">Informações</option>
                    <option value="B">Bloco de código</option>
                </select>
            </div>
        </div>
        <div class="mb-4">
            <label for="title" class="form-label">Título</label>
            <input type="text" class="form-control" name="note_title" id="title" placeholder="Escreva um título para a nota">
        </div>

        <input id="x" value="" type="hidden" name="note">
        <trix-editor input="x"></trix-editor>
        <button type="submit" class="btn btn-success mt-4">Gravar texto</button>
    </form>
</div>