<div class="container mt-5">
    <h1 class="text-center mb-3">Anotações</h1>

    <div class="row justify-content-end mb-5">
        <div class="col-2 ">
            <a href="add_note" class="btn btn-success ">Adicionar nova nota</a>
        </div>
    </div>
    <hr>
    <div class="listagem row">
        <ul class="justify-content-between ps-5 pe-5">
            <li>Assunto</li>
            <li>Tipo</li>
            <li>Titulo</li>
            <li>Data</li>
            <li></li>
            <li></li>
        </ul>
        <?php foreach ($this->viewData->listagem_anotacoes as $note) { ?>
            <ul class="justify-content-between ps-5 pe-5">
                <li><?php foreach ($this->viewData->listagem_assuntos as $subject) {
                        if ($subject['IDSUBJECT'] == $note['ID_SUBJECT']) {
                            echo $subject['subject'];
                        }
                    }
                    $note['ID_SUBJECT'] ?></li>
                <li><?= $note['type_of_note'] ?></li>
                <li><?= $note['note_title'] ?></li>
                <li><?= $note['note_date'] ?></li>
                <div class="d-flex flex-row">
                    <li class="me-2"><a href="" class="btn btn-success">Edit</a></li>
                    <li class="me-2"><a href="" class="btn btn-danger">Delete</a></li>
                </div>
            </ul>
        <?php } ?>
    </div>


</div>