<main>

    <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">

            <div class="carousel-item active">
                <img class="carousel-img" src="" alt="">
                <div class="container">
                    <div class="carousel-caption text-start">
                        <div class="row">
                            <h1 class="col-10"><?= $this->viewData->reviewCurses[0]['curse_title'] ?></h1>
                            <img class="subject-img col-2" src="<?= $this->viewData->reviewCurses[0]['sub_image'] ?>" alt="">
                        </div>
                        <p><span><img src=" <?= $this->viewData->reviewCurses[0]['school_image'] ?>" width="80px" alt=""></span> <?= $this->viewData->reviewCurses[0]['school'] ?></p>
                        <p><a class=" btn btn-lg btn-primary <?= $this->setHtmlData->signed ?>" href="list_classes?id=<?= $this->viewData->reviewCurses[0]['IDCURSE'] ?>">Ver agora</a></p>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <img class="carousel-img" src="" alt="">

                <div class="container">
                    <div class="carousel-caption">
                        <div class="row">
                            <h1 class="col-10"><?= $this->viewData->reviewCurses[1]['curse_title'] ?></h1>
                            <img class="subject-img col-2" src="<?= $this->viewData->reviewCurses[1]['sub_image'] ?>" alt="">
                        </div>
                        <p><span><img src="<?= $this->viewData->reviewCurses[1]['school_image'] ?>" width="80px" alt=""></span> <?= $this->viewData->reviewCurses[1]['school'] ?></p>
                        <p><a class="btn btn-lg btn-primary <?= $this->setHtmlData->signed ?>" href="list_classes?id=<?= $this->viewData->reviewCurses[1]['IDCURSE'] ?>">Ver agora</a></p>
                    </div>
                </div>
            </div>
            <div class="carousel-item">

                <img class="carousel-img" src="" alt="">
                <div class="container">
                    <div class="carousel-caption text-end">
                        <div class="row">

                            <img class="subject-img col-2" src="<?= $this->viewData->reviewCurses[2]['sub_image'] ?>" alt="">
                            <h1 class="col-10"><?= $this->viewData->reviewCurses[2]['curse_title'] ?></h1>
                        </div>
                        <p><span><img src="<?= $this->viewData->reviewCurses[2]['school_image'] ?>" width="80px" alt=""></span> <?= $this->viewData->reviewCurses[2]['school'] ?></p>
                        <p><a class=" btn btn-lg btn-primary <?= $this->setHtmlData->signed ?>" href="list_classes?id=<?= $this->viewData->reviewCurses[2]['IDCURSE'] ?>">Ver agora</a></p>
                    </div>
                </div>
            </div>

        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>


    <!-- Marketing messaging and featurettes
  ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing">
        <!-- Three columns of text below the carousel -->
        <div class="row">
            <?php foreach ($this->viewData->ultimas_notas as $nota) { ?>
                <div class="col-lg-4 d-flex flex-column align-items-center justify-content-between">
                    <img src="<?php foreach ($this->viewData->subjects as $subject) {
                                    if ($subject['IDSUBJECT'] == $nota['ID_SUBJECT']) {
                                        echo $subject['subject_image'];
                                    }
                                } ?>" alt="" class="circle-img">
                    <h2><?= empty($nota['note_title']) ? 'A' : $nota['note_title'] ?></h2>

                    <p class="mt-4">
                        <a class="btn btn-secondary" href="view_note?id=<?= $nota['IDNOTE'] ?>">Ver texto &raquo;</a>
                    </p>
                </div><!-- /.col-lg-4 -->
            <?php } ?>
        </div><!-- /.row -->


        <!-- START THE FEATURETTES -->

        <?php foreach ($this->viewData->classes as $class) { ?>
            <hr class="featurette-divider">

            <div class="row featurette">
                <div class="col-md-7">
                    <h2 class="featurette-heading"><?= $class['curse'] ?> -
                        <span class="text-muted">Aula <?= $class['class_number'] ?>
                            <?= $class['class_title'] ?></span>
                    </h2>

                    <p class="lead"><?= $class['include_date'] ?></p>
                </div>
                <div class="col-md-5">
                    <title>Placeholder</title>
                    <img class="border border-dark border-opacity-25" src="<?= $class['class_image_path'] ?>" alt="" width="500">
                </div>
            </div>

        <?php } ?>


        <hr class="featurette-divider">

        <!-- /END THE FEATURETTES -->

    </div><!-- /.container -->


    <!-- FOOTER -->
    <footer class="container">
        <p class="float-end"><a href="#">Back to top</a></p>
        <p>&copy; 2017–2021 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
    </footer>
</main>