<main class="container mt-5">
    <div class="d-flex flex-row justify-content-around align-items-center">
        <img src="<?php foreach ($this->viewData->subjects as $subject) {
                        if ($subject['IDSUBJECT'] == $this->viewData->note['ID_SUBJECT']) {
                            echo $subject['subject_image'];
                        }
                    } ?>" alt="" class="circle-img">
        <h2><?= $this->viewData->note['note_title'] ?></h2>
    </div>
    <div class="d-flex justify-content-between flex-row">

        <div><?= $this->viewData->note['note_date'] ?></div>
        <a href="<?= $this->setHtmlData->return ?>" class="btn btn-danger">Voltar</a>
    </div>
    <hr>
    <div>
        <?= $this->viewData->note['note'] ?>
    </div>
</main>