<div class="container mt-5">
    <h1 class="text-center mb-3">Listagem de Subtitulos</h1>
    <h2><?= $this->viewData->curse['curse_title'] ?></h2>
    <div class="row justify-content-end mb-5">
        <div class="col-2 ">
            <a href="add_subtitle?id=<?= $this->viewData->curse['IDCURSE'] ?>" class="btn btn-success ">Adicionar Subtítulo</a>
        </div>
        <div class="col-2">
            <a href="list_curses" class="btn btn-danger ">Voltar</a>
        </div>
    </div>
    <hr>
    <div class="listagem-sem-cabecalho row">
        <?php foreach ($this->viewData->list_subtitles as $subtitle) { ?>
            <ul class="row justify-content-between">
                <div class="col-8 row flex-fill">
                    <li class="col-3"> <?= $subtitle['subtitle'] ?></li>
                    <li class="col-3"> <?= $subtitle['subtitle_number'] ?></li>
                </div>
                <div class="col-4 d-flex flex-row">

                    <li class="me-2"><a href="edit_subtitle?id=<?= $this->viewData->curse['IDCURSE'] ?>&subtitle=<?= $subtitle['IDSUBTITLE'] ?>" class="btn btn-success">Edit</a></li>
                    <li class="me-2"><a href="delete_subtitle?id=<?= $subtitle['IDSUBTITLE'] ?>" class="btn btn-danger">Delete</a></li>
                </div>
            </ul>
        <?php } ?>
    </div>
</div>