<div class="container">

    <h1>Adiciona Assunto</h1>
    <div class="mb-3">

        <form action="<?= isset($this->viewData->subject) ? 'change_subject' : 'save_subject' ?>" method="POST" enctype="multipart/form-data">
            <input type="hidden" name="idsubject" value="<?= $this->viewData->subject['IDSUBJECT'] ?? '' ?>">
            <label for="subject" class="form-label">Subject</label>
            <input type="text" class="form-control" name="subject" id="subject" value="<?= $this->viewData->subject['subject'] ?? '' ?>">
            <label for="subject_file" class="form-label">Subject</label>
            <?php if (isset($this->viewData->subject)) { ?>
                <div class="alert alert-primary" role="alert">
                    <p>Last saved file: <span><?= $this->viewData->subject['subject_image'] ?? 'No file saved' ?></span></p>
                <?php } ?>
                </div>
                <input type="file" class="form-control" id="subject_file" aria-describedby="inputGroupFileAddon04" aria-label="Upload" name="upload_file" accept="image/jpeg,.gif,.png">
                <div class="row">
                    <button type="submit" class="btn btn-secondary mt-4 me-2 col-2">Salvar</button>
                    <a href="list_subjects" class="btn btn-danger mt-4  ms-2 col-2">Voltar</a>
                </div>
        </form>
    </div>
</div>