<div class="container mt-5">
    <h1 class="text-center mb-3">Listagem de assuntos</h1>

    <div class="row justify-content-end mb-5">
        <div class="col-2 ">
            <a href="add_subject" class="btn btn-success ">Adicionar Assunto</a>
        </div>
    </div>
    <hr>
    <div class="listagem-sem-cabecalho row">
        <?php foreach ($this->viewData->listagem_assuntos as $subject) { ?>
            <ul class="justify-content-between ps-5 pe-5">
                <div class="row flex-fill">
                    <li class="col-2"><img src="<?= $subject['subject_image'] ?>" alt="" style="height: 40px;"></li>
                    <li class="col"><?= $subject['subject'] ?></li>
                </div>
                <div class="d-flex flex-row">
                    <li class="me-2"><a href="edit_subject?id=<?= $subject['IDSUBJECT'] ?>" class="btn btn-success">Edit</a></li>
                    <li class="me-2"><a href="delete_subject?id=<?= $subject['IDSUBJECT'] ?>" class="btn btn-danger">Delete</a></li>
                </div>
            </ul>
        <?php } ?>
    </div>
</div>