<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Miniframework</title>
    <link rel="stylesheet" href="../css/bootstrap.min.css">
    <link href="../css/carousel.css" rel="stylesheet">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">Notes Center</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">Lista de Assuntos</a>
                        </li>
                        <li class="nav-item <?php echo $this->setHtmlData->signed === 'disabled' ? 'd-1' : 'd-none'; ?>">
                            <a class="nav-link" href="/signin">Sign In</a>
                        </li>
                        <li class="nav-item <?php echo $this->setHtmlData->signed === 'disabled' ? 'd-none' : 'd-1'; ?>">
                            <a class="nav-link" href="/log_out">Log out</a>
                        </li>
                        <li class="nav-item">
                            <div class="dropdown">
                                <button class="btn btn-outline-secondary dropdown-toggle  <?= $this->setHtmlData->signed ?>" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Adicionar Anotações
                                </button>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="#">Anotação</a></li>
                                    <li><a class="dropdown-item" href="#">Assunto</a></li>
                                    <li><a class="dropdown-item" href="list_user">Usuário</a></li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>

    <?php $this->content() ?>


    <script src="../js/jquery-3.6.0.min.js"></script>
    <script src="../js/bootstrap.bundle.min.js"></script>
</body>

</html>